Repository ansible/dispatcherd, pull requests merged in 2025-03, with the labels that each got.

#91 Start pattern to disallow untyped functions, MyPY updates
  .github/workflows/ci.yml
  Makefile
  dispatcher/control.py
  dispatcher/protocols.py
  mypy.ini
Labels: testing, refactoring

#118 Fix missing `await`
  dispatcher/producers/scheduled.py
  dispatcher/service/main.py
  dispatcher/service/next_wakeup_runner.py
  dispatcher/service/pool.py
  tests/unit/service/test_next_wakeup_runner.py
Labels: bug

#111 Split logic for task blocking and queuing into a new module
  dispatcher/control.py
  dispatcher/producers/on_start.py
  dispatcher/producers/scheduled.py
  dispatcher/protocols.py
  dispatcher/service/asyncio_tasks.py
  dispatcher/service/blocker.py
  dispatcher/service/control_tasks.py
  dispatcher/service/main.py
  dispatcher/service/next_wakeup_runner.py
  dispatcher/service/pool.py
  dispatcher/service/queuer.py
  dispatcher/utils.py
  tests/integration/test_main.py
  tests/unit/service/producers/test_scheduled_producer.py
  tests/unit/service/test_asyncio_tasks.py
  tests/unit/service/test_pool.py
Labels: refactoring

#120 Detect and clean up unexpectedly terminated worker processes
  dispatcher/service/pool.py
  tests/unit/service/test_worker_liveness.py
Labels: awx, MVP

#113 Add a `dispatcherctl` command, rework the demo with it
  Makefile
  README.md
  dispatcher/cli.py
  docker-compose.yml
  docs/config.md
  pyproject.toml
  run_demo.py
  tools/demo/Dockerfile
Labels: enhancement, testing

#123 UNLISTEN when done with session
  dispatcher/brokers/pg_notify.py
Labels: bug

#125 Add Unix socket broker
  Makefile
  dispatcher.yml
  dispatcherd/brokers/pg_notify.py
  dispatcherd/brokers/socket.py
  dispatcherd/control.py
  dispatcherd/factories.py
  dispatcherd/producers/brokered.py
  dispatcherd/protocols.py
  dispatcherd/service/main.py
  schema.json
  tests/conftest.py
  tests/integration/brokers/test_socket.py
  tests/integration/test_socket_use.py
Labels: enhancement
